### ISSUE TITLE
Add CFC image sensor support

### ISSUE THREAD

**Issue by oliver-rew** [oresat/oresat-linux-prucam#41]

**Comment by oliver-rew** [comment]
TODO:
- add rest of PIRT1280 registers to python library
- add query params to set different params
- daemonize the PIRT1280 control server
- add background temperature control to server
- add options to return PNG, raw sensor values, or maybe FITS
- Test with Windows
- setup SSH/SCP instructions

**Comment by ryanpdx** [comment]
moved to its own repo: https://github.com/oresat/oresat-prucam-pirt1280
