### ISSUE TITLE
ti-pru-cgt-installer

### ISSUE THREAD

**Issue by jinsanko** [oresat/oresat-linux-prucam#42]
Thank for your work.
Can you provide me more information on where I can locate the "ti-pru-cgt-installer" package?
"Install dependencies: $ sudo apt install ti-pru-cgt-installer"
I use a newly installed Ubuntu 18.04 to study your code.

Best Regards
Jinsan Ko

**Comment by ryanpdx** [comment]
Hello,

`ti-pru-cgt-installer` deb package is from the rcn-ee apt repo a http://repos.rcn-ee.com/debian/. It can be added by adding 
`deb-src [arch=armhf] http://repos.rcn-ee.com/debian/ buster main` to `/etc/apt/sources.list` but that package is only for `armhf` systems.

That package is basically a wrapper for `wget` call to download the _PRU Code Generation Tools - Compiler_ for ARM-A8 systems from https://www.ti.com/tool/download/PRU-CGT-2-1.

**Comment by jinsanko** [comment]
Thank for your help. Here is my current status.

jsk@ubuntu:~$ sudo mv sources.list /etc/apt/sources.list
jsk@ubuntu:~$ sudo apt-get update
Hit:1 http://repos.rcn-ee.com/debian buster InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                            
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                                    
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                     
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Reading package lists... Done                     
jsk@ubuntu:~$ sudo add-apt-repository 'deb [arch=armhf] http://repos.rcn-ee.com/debian/ buster main'
Hit:1 http://repos.rcn-ee.com/debian buster InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                       
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                              
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
jsk@ubuntu:~$ sudo apt-get install ti-pru-cgt-installer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ti-pru-cgt-installer
jsk@ubuntu:~$

**Comment by ryanpdx** [comment]
Sorry about the non response.

That package is only available for armv7 machines. You will need to download and install manually for other architectures from https://www.ti.com/tool/download/PRU-CGT-2-1.
